[package]
name = "tension"
version = "0.1.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2021"
description = "Generic tensor library"
documentation = "https://docs.rs/tension"
readme = "README.md"
homepage = "https://github.com/agerasev/tension"
repository = "https://github.com/agerasev/tension"
license = "MIT OR Apache-2.0"
keywords = ["tensor", "ml"]
categories = ["algorithms", "mathematics", "science"]

[dependencies]
num-traits = "0.2"
num-integer = "0.1"
num-complex = "0.3"
